### ISSUE TITLE
Rename click event method names

### ISSUE THREAD

**Issue by CakeWithDivinity** [Gobidev/auto-locus#1]
Hey, 
I do really enjoy your program. I really missed a simple tool, which could calculate the bend points.
But now to the topic of the issue: 
The names of the methods do not say which button they are linked to. I would suggest changing them to a name like `calculate_locus_button_click`.

- [ ] https://github.com/Gobidev/auto-locus/blob/master/Auto_Locus.py#L11
- [ ] https://github.com/Gobidev/auto-locus/blob/master/Auto_Locus.py#L72 

It is just some refactoring. So it should be fixed within a few minutes. If you do not have enough time, i could do this for you. But you can choose :)

**Comment by Gobidev** [comment]
Fixed in #2
